# workflows do not have same permissions across forks pr. from same repo (branch to branch)
# labeler cant write across forks https://github.com/actions/labeler/issues/12
# but has now been fixed https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
name: Labeler
on: [pull_request_target]

jobs:
  label:
    runs-on: windows-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"