# workflows do not have same permissions across forks pr. from same repo (branch to branch)
# labeler cant write across forks https://github.com/actions/labeler/issues/12
# but has now been fixed https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
name: Labeler
on: [pull_request_target]

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: windows-latest
    steps:
      - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"